# Generated by Django 2.2.7 on 2019-11-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='FundCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'fundcategories',
            },
        ),
        migrations.CreateModel(
            name='FundMainAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.SmallIntegerField(null=True)),
                ('q2', models.SmallIntegerField(null=True)),
                ('q3', models.CharField(max_length=100, null=True)),
                ('q4', models.CharField(max_length=100, null=True)),
                ('is_commision_aggreed', models.BooleanField(default=False)),
                ('is_futureopen_aggreed', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundmainagreements', to='fund.Document')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Maker')),
            ],
            options={
                'db_table': 'fundmainagreements',
            },
        ),
        migrations.CreateModel(
            name='FundMainInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('goal_money', models.IntegerField(null=True)),
                ('main_image', models.URLField(blank=True, max_length=500, null=True)),
                ('deadline', models.DateField(null=True)),
                ('is_adult_agreed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundmaininformations', to='fund.FundCategory')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Maker')),
            ],
            options={
                'db_table': 'fundmaininformations',
            },
        ),
        migrations.CreateModel(
            name='FundMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('company_image', models.URLField(max_length=500, null=True)),
                ('cs_email', models.CharField(max_length=50, null=True)),
                ('cs_number', models.SmallIntegerField(null=True)),
                ('ceo_name', models.CharField(max_length=50, null=True)),
                ('ceo_email', models.CharField(max_length=50, null=True)),
                ('kakao_id', models.CharField(max_length=50, null=True)),
                ('kakao_link', models.CharField(max_length=200, null=True)),
                ('hompage', models.CharField(max_length=500, null=True)),
                ('sna1', models.CharField(max_length=100, null=True)),
                ('sns2', models.CharField(max_length=100, null=True)),
                ('sns3', models.CharField(max_length=100, null=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Maker')),
            ],
            options={
                'db_table': 'fundmakers',
            },
        ),
        migrations.CreateModel(
            name='FundPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=100, null=True)),
                ('q2', models.IntegerField(null=True)),
                ('q3', models.CharField(max_length=100, null=True)),
                ('q4', models.CharField(max_length=100, null=True)),
                ('is_auth_agreed', models.BooleanField(null=True)),
                ('is_commision', models.BooleanField(null=True)),
                ('is_opened', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'fundpolicies',
            },
        ),
        migrations.CreateModel(
            name='FundProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_main_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fund.FundMainAgreement')),
                ('fund_main_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fund.FundMainInformation')),
                ('fund_makers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fund.FundMaker')),
                ('fund_policies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fund.FundPolicy')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Maker')),
            ],
            options={
                'db_table': 'fundprojects',
            },
        ),
        migrations.CreateModel(
            name='FundReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('introduction', models.CharField(max_length=300, null=True)),
                ('limitation', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'fundrewards',
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'policydocumets',
            },
        ),
        migrations.CreateModel(
            name='RewardDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'rewarddeliveries',
            },
        ),
        migrations.CreateModel(
            name='RewardOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, null=True)),
                ('fund_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.FundReward')),
                ('fund_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.FundProject')),
            ],
            options={
                'db_table': 'rewardoptions',
            },
        ),
        migrations.CreateModel(
            name='FundStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_image', models.URLField(max_length=500, null=True)),
                ('summary', models.CharField(max_length=1000, null=True)),
                ('is_agreed', models.BooleanField()),
                ('main_image', models.URLField(max_length=500, null=True)),
                ('context', models.CharField(max_length=5000, null=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Maker')),
            ],
            options={
                'db_table': 'fundstories',
            },
        ),
        migrations.CreateModel(
            name='FundRewardMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.FundProject')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Maker')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.FundReward')),
            ],
            options={
                'db_table': 'fundrewardmappings',
            },
        ),
        migrations.AddField(
            model_name='fundreward',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fund.RewardDelivery'),
        ),
        migrations.AddField(
            model_name='fundpolicy',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.PolicyDocument'),
        ),
        migrations.AddField(
            model_name='fundpolicy',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Maker'),
        ),
    ]
