# Generated by Django 2.2.7 on 2019-11-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundmaker',
            old_name='sna1',
            new_name='sns1',
        ),
    ]
