# Generated by Django 2.2.7 on 2019-11-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_auto_20191120_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundmainagreement',
            old_name='is_commision_aggreed',
            new_name='is_commision_agreed',
        ),
        migrations.RenameField(
            model_name='fundmainagreement',
            old_name='is_futureopen_aggreed',
            new_name='is_futureopen_agreed',
        ),
    ]
