# Generated by Django 2.2.7 on 2019-11-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_auto_20191120_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundmaker',
            name='cs_number',
            field=models.IntegerField(null=True),
        ),
    ]
