# Generated by Django 2.2.7 on 2019-11-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_auto_20191120_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FundStory',
        ),
    ]
