# Generated by Django 2.2.7 on 2019-11-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maker',
        ),
    ]
