# Generated by Django 2.2.7 on 2019-11-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191119_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_login_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_social', to='account.SocialPlatform'),
        ),
    ]
