# Generated by Django 2.2.7 on 2019-11-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191120_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('is_agreed', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.User')),
            ],
            options={
                'db_table': 'makers',
            },
        ),
    ]
