# Generated by Django 2.2.7 on 2019-11-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
